FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
COPY ../config /config

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "main:app"]
